name: Order Notification

on:
  workflow_dispatch:
  repository_dispatch:
    types: [order_placed]

jobs:
  send_notification:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Send Notification
      run: |
        echo "Order placed by ${{ github.event.client_payload.name }}"
        echo "Email: ${{ github.event.client_payload.email }}"
        echo "Phone: ${{ github.event.client_payload.phone }}"
        echo "Menu: ${{ github.event.client_payload.menu }}"
        echo "Quantity: ${{ github.event.client_payload.quantity }}"
        echo "Total Price: ${{ github.event.client_payload.totalPrice }}"
        # Here you can add code to send an email or notification using a service like SendGrid or Mailgun
